ALTER TABLE requests
    ADD COLUMN IF NOT EXISTS status VARCHAR(32) NOT NULL DEFAULT 'new' AFTER comment,
    ADD COLUMN IF NOT EXISTS status_note TEXT NULL AFTER status,
    ADD COLUMN IF NOT EXISTS status_updated_at INT UNSIGNED NOT NULL DEFAULT 0 AFTER status_note;
